modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]] #mandatory
modId="paimeng"
version="1.16.5-1.2.5"
displayName="PaiMeng"
authors="yuo" 
description='''
应急食品。1.16.5。
部分素材纹理来自《原神》。
'''
[[dependencies.paimeng]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5, 1.17)"
    ordering="NONE"
    side="BOTH"
